package server.dto;

public enum SuccessResponse {
    GET_ROOM_LIST_SUCCESS,
    FIND_ROOM_SUCCESS,
    ENTER_ROOM_SUCCESS,
    GET_CHAT_HISTORY_SUCCESS,
    SEND_CHAT_SUCCESS,
    EXIT_ROOM_SUCCESS,
    VOTE_DISCUSSION_SUCCESS,
    LIKE_CHAT_SUCCESS,
    CREATE_ROOM_SUCCESS
}
